### ISSUE TITLE
is this like the keywhiz plugin but for hashicorp's vault?

### ISSUE THREAD

**Issue by joeblackwaslike** [calavera/docker-volume-vault#2]
is this like the keywhiz plugin but for hashicorp's vault?  sounds like it's probably in a rough state atm, i may be able to find some time to contribute. anything i should know right off if so?  

thx

**Comment by calavera** [comment]
Yup, It's in a better state that the readme suggests though. Although it needs a huge refactor of the filesystem. I was considering moving all Fuse related stuff to https://github.com/bazil/fuse. It's a more human friendly framework.
